LIBTARGET	:= libGSLMATRIX
SOURCES		:=  init.c matrix.c file.c rowcol.c swap.c copy.c minmax.c prop.c oper.c getset.c view.c submatrix.c view.h 
CFLAGS		:= -DADD_ -I../GSL-include
CXXFLAGS	:= -DADD_ -I../GSL-include

include ../Makefile.common
