LIBTARGET	:= libGSLLINALG
SOURCES		:= multiply.c exponential.c tridiag.c tridiag.h lu.c luc.c hh.c qr.c qrpt.c lq.c ptlq.c svd.c householder.c householdercomplex.c hessenberg.c hesstri.c cholesky.c choleskyc.c symmtd.c hermtd.c bidiag.c balance.c balancemat.c
CFLAGS		:= -DADD_ -I../GSL-include
CXXFLAGS	:= -DADD_ -I../GSL-include

include ../Makefile.common
