LIBTARGET	:= libGSLVECTOR
SOURCES		:= copy.c minmax.c subvector.c view.c init.c reim.c file.c oper.c prop.c swap.c vector.c
CFLAGS		:= -DADD_ -I../GSL-include
CXXFLAGS	:= -DADD_ -I../GSL-include

include ../Makefile.common
